before_install:
  - gem install cocoapods -v '1.0.1'
language: objective-c
osx_image: xcode7.3
podfile: Example/Podfile

script:
  xctool
  -workspace Example/DRAuraButton.xcworkspace
  -scheme DRAuraButton
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
  build 
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

